### ISSUE TITLE
Default RST pin status should be HIGH 

### ISSUE THREAD

**Issue by LeAmarillo** [RobTillaart/DRV8825#9]
Hi Rob,

Thanks for providing the library for DRV8825 stepper driver. It saved me a lot of time to organizing the bottom codes. However, I found one issue in the source code. 

In DRV8825.cpp line 39, the RST pin is set to be LOW during the initialization.

>if (RST != 255)
  {
    _resetPin = RST;
    pinMode(_resetPin, OUTPUT);
    digitalWrite(_resetPin, LOW);    //  page 3
  }

However, according to the manufacturer 's page (https://www.pololu.com/product/2133), it is said in the 'Control inputs' part that:

>These default RESET and SLEEP states are ones that prevent the driver from operating; both of these pins must be high to enable the driver (they can be connected directly to a logic “high” voltage between 2.2 and 5.25 V, or they can be dynamically controlled via connections to digital outputs of an MCU).

I spent some time to figure out this problem and once I set the default status of the RST pin to HIGH, everything works. I am not sure if that is due to some recent updates of the hardware or a typo in the code. Just want to report this for the DRV8825 community. Thanks!

**Comment by RobTillaart** [comment]
Thanks for this issue, 
Sounds like a serious problem so it will get some priority.
I will check with my version of the datasheet.

**Comment by RobTillaart** [comment]
@LeAmarillo
- Created a develop branch and a PR which should fix the issue. (build is running)
- Version will become 0.2.0
- Added an example to test RESET and SLEEP
- Some pending changes are included too.

As I do not have a test setup at the moment, do you have time to verify the develop branch?
Thanks in advance
